spring.application.name=fswd-mobile-banking-api

#Config bean of DataSource
spring.datasource.url=jdbc:postgresql://localhost:9999/fswd_mobile_banking_db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=1234
spring.datasource.password=postgres

spring.security.user.name=polin
spring.security.user.password=polin@123

spring.servlet.multipart.max-request-size=20MB
spring.servlet.multipart.max-file-size=10MB

media.server-path=/home/polin/Desktop/Spring/fswd-1st-afternoon-spring-projects/Media/
media.base-uri=http://localhost:8080/media/

#Config JPA Hibernate DDL
#DDL = Data Definition Language
#CREATE, ALTER, RENAME, ...
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9999/realms/aft-mb-api
